// apps/site/pages/docs/player/[lib]/[2]components/[1]providers/[2]video/_snippets/react/usage.tsx
import { Video } from '@vidstack/player-react';

function Media() {
  return (
    <Video poster="https://media-files.vidstack.io/poster.png">
      <video
        controls
        preload="none"
        src="https://media-files.vidstack.io/720p.mp4"
        poster="https://media-files.vidstack.io/poster-seo.png"
      />
    </Video>
  );
}

// apps/site/pages/docs/player/[lib]/[2]components/[1]providers/[2]video/_previews/usage.svelte
<script>
  import { Media, Video, AspectRatio } from '@vidstack/player/svelte';
</script>

<Media class="w-11/12 max-w-lg mx-auto">
  <AspectRatio class="w-full" ratio="16/9">
    <Video controls poster="https://media-files.vidstack.io/poster.png">
      <video
        controls
        preload="none"
        src="https://media-files.vidstack.io/720p.mp4"
        poster="https://media-files.vidstack.io/poster-seo.png"
      >
        <track kind="captions" />
      </video>
    </Video>
  </AspectRatio>
</Media>
